const styles = {
    container: {
      padding: '20px',
      fontFamily: "'Roboto', sans-serif",
      maxWidth: '1000px',
      margin: '0 auto',
      backgroundColor: '#f0f2f5',
    },
    header: {
      display: 'flex',
      alignItems: 'center',
      marginBottom: '20px',
    },
    logo: {
      height: '60px',
      marginRight: '15px',
    },
    title: {
      textAlign: 'left',
      color: '#333',
      fontSize: '32px',
      fontWeight: 'bold',
    },
    message: {
      color: 'green',
      textAlign: 'center',
    },
    error: {
      color: 'red',
      textAlign: 'center',
    },
    authContainer: {
      border: '1px solid #ccc',
      padding: '30px',
      borderRadius: '8px',
      backgroundColor: '#fff',
      marginTop: '20px',
      boxShadow: '0 2px 5px rgba(0,0,0,0.1)',
    },
    form: {
      display: 'flex',
      flexDirection: 'column',
      marginBottom: '15px',
    },
    input: {
      padding: '12px',
      marginBottom: '15px',
      borderRadius: '5px',
      border: '1px solid #ccc',
      fontSize: '16px',
      width: '100%',
      boxSizing: 'border-box',
    },
    label: {
      marginBottom: '10px',
      fontWeight: 'bold',
    },
    primaryButton: {
      padding: '12px',
      backgroundColor: '#007bff',
      color: 'white',
      border: 'none',
      borderRadius: '5px',
      fontSize: '16px',
      cursor: 'pointer',
      marginBottom: '10px',
      transition: 'background-color 0.3s',
    },
    editButton: {
      padding: '10px',
      backgroundColor: '#ffc107',
      color: 'white',
      border: 'none',
      borderRadius: '5px',
      fontSize: '14px',
      cursor: 'pointer',
      marginRight: '10px',
      transition: 'background-color 0.3s',
    },
    deleteButton: {
      padding: '10px',
      backgroundColor: '#dc3545',
      color: 'white',
      border: 'none',
      borderRadius: '5px',
      fontSize: '14px',
      cursor: 'pointer',
      transition: 'background-color 0.3s',
    },
    cancelButton: {
      padding: '12px',
      backgroundColor: '#6c757d',
      color: 'white',
      border: 'none',
      borderRadius: '5px',
      fontSize: '16px',
      cursor: 'pointer',
      marginTop: '10px',
      transition: 'background-color 0.3s',
    },
    googleButton: {
      padding: '12px',
      backgroundColor: '#db4437',
      color: 'white',
      border: 'none',
      borderRadius: '5px',
      fontSize: '16px',
      cursor: 'pointer',
      marginBottom: '15px',
      transition: 'background-color 0.3s',
    },
    logoutButton: {
      padding: '10px',
      backgroundColor: '#dc3545',
      color: 'white',
      border: 'none',
      borderRadius: '5px',
      fontSize: '14px',
      cursor: 'pointer',
      float: 'right',
      marginTop: '10px',
      transition: 'background-color 0.3s',
    },
    linkButton: {
      background: 'none',
      color: '#007bff',
      border: 'none',
      padding: '0',
      fontSize: '16px',
      textDecoration: 'underline',
      cursor: 'pointer',
    },
    courseGrid: {
      display: 'flex',
      flexWrap: 'wrap',
      marginTop: '20px',
      justifyContent: 'space-between',
    },
    courseCard: {
      backgroundColor: '#fff',
      padding: '20px',
      margin: '10px 0',
      borderRadius: '8px',
      width: 'calc(48% - 20px)',
      boxSizing: 'border-box',
      boxShadow: '0 2px 5px rgba(0,0,0,0.1)',
      transition: 'transform 0.2s',
    },
    navBar: {
      marginTop: '20px',
      marginBottom: '20px',
      display: 'flex',
      justifyContent: 'center',
    },
    tab: {
      padding: '10px 20px',
      backgroundColor: '#6c757d',
      color: 'white',
      border: 'none',
      borderRadius: '5px',
      marginRight: '10px',
      cursor: 'pointer',
      fontSize: '16px',
      transition: 'background-color 0.3s',
    },
    activeTab: {
      padding: '10px 20px',
      backgroundColor: '#007bff',
      color: 'white',
      border: 'none',
      borderRadius: '5px',
      marginRight: '10px',
      cursor: 'pointer',
      fontSize: '16px',
    },
    cardButtons: {
      marginTop: '15px',
    },
    teamGrid: {
      display: 'flex',
      flexWrap: 'wrap',
      justifyContent: 'center',
      marginTop: '20px',
    },
    teamMemberCard: {
      backgroundColor: '#fff',
      padding: '20px',
      margin: '10px',
      borderRadius: '8px',
      width: '200px',
      boxSizing: 'border-box',
      boxShadow: '0 2px 5px rgba(0,0,0,0.1)',
      textAlign: 'center',
    },
    teamMemberImage: {
      width: '100%',
      height: 'auto',
      borderRadius: '50%',
      marginBottom: '15px',
    },
    linkedinIcon: {
      width: '24px',
      height: '24px',
      marginTop: '10px',
    },
  };

export default styles;